#
# GitLab CI configuration.
#
# https://docs.gitlab.com/ee/ci/yaml
#

stages:
  - Pipeline

#
# Jobs.
#

# Properties we can't set with `default`.
.default:
  stage: Pipeline

.child:
  extends:
    - .default
  trigger:
    forward:
      pipeline_variables: false
      yaml_variables: false
    strategy: depend

Source:
  extends:
    - .child
  trigger:
    include: .gitlab/pipelines/.source.yml
  interruptible: true

Beta:
  extends:
    - .child
  needs:
    - Source
  rules:
    # Default branch push.
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    # Tag push.
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_TAG != null
  resource_group: Beta
  environment:
    name: Beta
    action: start
  trigger:
    include: .gitlab/pipelines/.beta.yml

Production:
  extends:
    - .child
  needs:
    - Beta
  rules:
    # Tag push.
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_TAG != null
  resource_group: Production
  environment:
    name: Production
    action: start
  trigger:
    include: .gitlab/pipelines/.production.yml
